version: "3.8"

services:
  app:
    container_name: travelhelp-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "5533:5533"
    # environment:
    #   - NODE_ENV=development
    # stdin_open: true
    # tty: true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
