FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --silent

# install only dependencies, and not devDependencies, regardless of the value of the NODE_ENV environment variable.
# RUN npm ci --slient --only=production

# docker-compose will do below steps instead.
# COPY . .
# CMD ["npm", "run", "dev"]