FROM node:14-alpine

WORKDIR /app

# Set node environment to production
ENV NODE_ENV test
ENV SERVER_PORT 3355

# Update the system
RUN apk --no-cache -U upgrade

# Install pm2
RUN npm install pm2@latest -g

COPY package*.json ./

# By adding `only production` option, install only production dependencies, regardless of the value of the NODE_ENV environment variable.
# npm ci will remove the existing npm_modules.
RUN npm ci --slient --only=production

COPY . .

EXPOSE 3355

CMD ["pm2-runtime", "ecosystem.config.yml"]
