FROM node:14-alpine

WORKDIR /app

# Update the system
RUN apk --no-cache -U upgrade

# Copy package.json & package-lock.json file
COPY package*.json ./

RUN npm install --silent

# docker-compose will replace below steps instead.
# COPY . .
# CMD ["npm", "run", "dev"]
