FROM node:14-alpine

# Github Actions recommend to not use the WORKDIR.
# See details here: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/dockerfile-support-for-github-actions#workdir
WORKDIR /app

# Update the system
RUN apk --no-cache -U upgrade

# Copy package.json & package-lock.json file
COPY package*.json ./

# Install pm2
RUN npm install pm2@latest -g

RUN npm install --silent

# By adding `only production` option, install only production dependencies, regardless of the value of the NODE_ENV environment variable.
# Once you install with only production npms, set the script file from './ecosystem.pm2.dev.config.yml' into app.js
# RUN npm install --silent --only=production

# Set node environment to development
ENV NODE_ENV development
ENV SERVER_PORT=3355
